//export const FORMULARIO_PROYECTO = "FORMULARIO_PROYECTO";
export const OBTENER_TODOS = "OBTENER_TODOS";
export const CREAR_TAREA = "CREAR_TAREA";
export const ELIMINAR_TAREA = "ELIMINAR_TAREA";
export const MODIFICAR_TAREA = "MODIFICAR_TAREA";
export const MODIFICAR_TAREA1 = "MODIFICAR_TAREA1";
